name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  servicea:
    name: Service A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - name: Running Service A
        working-directory: ./servicea
        run: mvn verify

